name: MistralOCR_Desktop

options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    macOS: "14.0"

configs:
  Debug: debug
  Release: release

settings:
  BASE_SDK: macosx
  MACOSX_DEPLOYMENT_TARGET: "14.0"

packages: {}

targets:
  MistralOCR_Desktop:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/App
      - path: Resources/App                  # <-- pas de "type: folder"
    entitlements:
      path: Entitlements/App.entitlements
    settings:
      INFOPLIST_FILE: Resources/App/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MistralOCR-Desktop
      SWIFT_VERSION: 5.10
      CODE_SIGN_ENTITLEMENTS: Entitlements/App.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: ShareExtension
    scheme: { testTargets: [] }

  ShareExtension:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/ShareExtension
      - path: Resources/ShareExtension       # <-- pas de "type: folder"
    entitlements:
      path: Entitlements/ShareExtension.entitlements
    settings:
      INFOPLIST_FILE: Resources/ShareExtension/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MistralOCR-Desktop.ShareExtension
      CODE_SIGN_ENTITLEMENTS: Entitlements/ShareExtension.entitlements
    scheme: { testTargets: [] }
